select * from DEPARTMENTS;
select FIRST_NAME from EMPLOYEES;
select FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES;
SELECT STREET_ADDRESS, POSTAL_CODE FROM LOCATIONS;
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;
select round(avg(SALARY),2) from EMPLOYEES;